### ISSUE TITLE
Installation of pymix-web exe into QmixSDK directory required

### ISSUE THREAD

**Issue by githubuser0xFFFF** [psyfood/pyqmix-web#34]
I downloaded and tested pyqmix-web_2018-11-07.exe but could not connect to the pumps. Then I copied the exe into the QmixSDK folder and now the connection to the device was successfully established.

So it would be good to add this information to the installation instructions.

**Comment by hoechenberger** [comment]
Dear @githubuser0xFFFF, thanks for the report, and great you found a workaround!

I believe this issue might be related to `pyqmix` not being able to discover (or load) the Qmix SDK DLLs. We have some sort of auto-discovery mechanism built-in that adds the DLL directory to the `PATH`, but it could but that it needs a bit of tweaking still.

If you feel like it, could you add the DLL directory to your `PATH` and see if `pyqmix-web` works even when not placed in that directory?

On another side note, we're currently preparing a new release that will make the web interface available for installation via `pip` and `conda` for interested users.

**Comment by githubuser0xFFFF** [comment]
Hi Richard,

adding the DLL directory to the PATH works. On Windows the application always searches in the current application path for the required DLL and then it uses the PATH variable. Would be great for not so experienced users to add this to the documentation. It would also be great, if you could add some information, where the application searches for the device configuration.

I noticed, that pymix-web lists the configurations from the folder C:\Users\Public\Documents\QmixElements\Projects\default_project. But if someone has not installed QmixElements, this folder will not exist. Or if someone uses the project feature from QmixElements (the recommended usage), the device configurations will be created in the project folder and not in the default project folder. So it would be good, to give the user the information, that it is required to copy the configuration to C:\Users\Public\Documents\QmixElements\Projects\default_project.

Kind regards,

Uwe Kindler form CETONI

**Comment by ArndalAndersen** [comment]
Hi Uwe, 
thanks for helping out. Indeed, we assume that the configurations are stored at
`C:\Users\Public\Documents\QmixElements\Projects\default_project`. I agree, we should really inform the user that configurations are drawn from here per default, or even better; allow the user to browse to a custom configuration-folder.
