### ISSUE TITLE
Misleading Error information

### ISSUE THREAD

**Issue by githubuser0xFFFF** [psyfood/pyqmix-web#35]
If I click the **detect pumps** button in pymix-web, and the application cannot find the required Qmix SDK DLLs, then the following error message is shown:

> **Error - no pumps were detected.**
> Check that (1) the pumps are powered on and connected to the computer, and (2) that the bus is not connected already. Then try again.

This leads the user into the wrong direction for fixing the issue. If the DLLs are not installed or cannot be found, a better error message would help a lot.

Kind regards, Uwe

**Comment by ArndalAndersen** [comment]
I agree Uwe, Thanks for the heads-up. 

/Camilla
