### ISSUE TITLE
Development and production build look different

### ISSUE THREAD

**Issue by hoechenberger** [psyfood/pyqmix-web#41]
Tested with `master`; not sure about `2019.1`.

Development:
<img width="1392" alt="Screen Shot 2019-05-04 at 17 01 45" src="https://user-images.githubusercontent.com/2046265/57180990-91151480-6e8e-11e9-92d5-3cd960f72770.png">

Production:
<img width="1392" alt="Screen Shot 2019-05-04 at 17 00 48" src="https://user-images.githubusercontent.com/2046265/57180991-996d4f80-6e8e-11e9-850e-8a68997659d7.png">

Probable cause:
https://stackoverflow.com/questions/37021225/webpack-build-css-rules-have-different-order-then-in-development

We again need to step through style sheets, I'm afraid…

**Comment by ArndalAndersen** [comment]
Wauw. That looks horrible ^^
I need some help reproducing your error - on my computers it all looks fine. I assume that by 'production' you mean that you fire up flask and access `http://localhost:5000/pyqmix-web/`? 

Also, you say it's tested with `master` and that you're unsure about release 2019.1. They should be identical at the moment though - which means that they should both contain all the recent changes I did to fix the style of the frontend-build. I must have missed some screen size criteria or something. Or did it occur after you updated the React scripts again? Any thoughts appreciated :)

**Comment by hoechenberger** [comment]
It seems this was a caching issue indeed. Super weird. I wonder if this might have to do with the [service worker](https://github.com/psyfood/pyqmix-web/blob/3a207b9da9169b784e9bfd53b3c81d3c90e15332/pyqmix_frontend/src/index.js#L9) we're currently using – it's the thing that allows the app to work even when offline, which doesn't make much sense in our case anyway, but may lead to caching issues! https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app

**Comment by ArndalAndersen** [comment]
This is exactly what I've been doing - using incognito windows. I must be a pro.

**Comment by hoechenberger** [comment]
I have not the slightest clue what's going on, but I started seeing this weird behavior again with `master` 😭

**Comment by hoechenberger** [comment]
Reinstalled, same issue. Reinstalled again, problem gone. Something seems to be weird here. But working again -- _for now!_
