### ISSUE TITLE
Allow users to set syringe parameters (diameter, piston stroke)

### ISSUE THREAD

**Issue by hoechenberger** [psyfood/pyqmix-web#6]
Potentially we should simply present the list of syringes that are pre-defined in `pyqmix.pump.QmixPump.set_syringe_params_by_type()`.

**Comment by ArndalAndersen** [comment]
I see that the syringe sizes are specified as a dictionary in Qmix.set_syringe_params_by_type. It would be smartest if I use this dictionary so we just have it specified one place. But how would I retrieve it?

**Comment by hoechenberger** [comment]
This is now resolved (via https://github.com/psyfood/pyqmix/pull/54)

Syringes can now be retrieved via
```python
from pyqmix.pumps import syringes
syringe_types = list(syringes.keys())  # Python 3 returns dict_keys object, not a list.
```
