### ISSUE TITLE
Remove DLL directory input form

### ISSUE THREAD

**Issue by hoechenberger** [psyfood/pyqmix-web#7]
Once https://github.com/psyfood/pyqmix/issues/51 is implemented, there will be no need to specify the DLL location via the web interface anymore.

**Comment by ArndalAndersen** [comment]
I removed the dll-input from the front-end. 
As an intermediate solution (until the pyqmix is updated), the backend finds the dll path by: appdirs.user_data_dir('QmixSDK', '').

**Comment by ArndalAndersen** [comment]
Once psyfood/pyqmix#56 has been merged, then this issue is solved by deleting these lines in the backend (app.py):

import appdirs
dll_dir = appdirs.user_data_dir('QmixSDK', '')
config.set_qmix_dll_dir(dll_dir)

**Comment by hoechenberger** [comment]
pyqmix has been updated accordingly via https://github.com/psyfood/pyqmix/pull/56. You can go ahead now and change the backend.
